import 'package:flutter/material.dart';
<<<<<<< HEAD
import 'package:flutter_application_1/Pages/login.dart';

void main() 
{
  runApp(const MyApp());
}

class MyApp extends StatelessWidget 
{
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) 
  {
    return MaterialApp
    (
=======
import 'Pages/login.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // Auto-generated by `flutterfire configure`

Future<void> main() async {
   WidgetsFlutterBinding.ensureInitialized();

  print("Loading .env...");
  await dotenv.load(fileName: "assets/.env");
  print("Loaded .env");

  print("Initializing Firebase...");
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  print("Firebase initialized");

  print("Running app...");
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
>>>>>>> b313f72212986cb00ce15a107eddd7f95281bec5
      debugShowCheckedModeBanner: false,
      theme: ThemeData(fontFamily: "Poppins"),
      home: const Login(),
    );
  }
<<<<<<< HEAD
}


=======
}
>>>>>>> b313f72212986cb00ce15a107eddd7f95281bec5
